version: 2.1
orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    docker:
    - image: circleci/android:api-29
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Todo/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Todo/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew assemble build lint test
      - store_artifacts:
          path: Todo/build/reports
          destination: reports
      - store_test_results:
          path: Todo/build/test-results
