version: 2.1
orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build
          command: ./gradlew assemble build lint test
       -run:
          name: Wait emulator
          command: |
           # wait for it to have booted
          circle-android wait-for-boot
           # unlock the emulator screen
          sleep 30
           adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedAndroidTest
      - store_artifacts:
          path: Todo/build/reports
          destination: reports
      - store_test_results:
          path: Todo/build/test-results
